#
# winLAME - a frontend for the LAME encoding engine
# Copyright (c) 2000-2019 Michael Fink
#
# AppVeyor build configuration file
#
version: 2.19.0.{build}

image: Visual Studio 2019

platform: Win32

configuration: Release

before_build:
  - ps: source\Patch-BuildVersion.ps1 -version $env:appveyor_build_version
  - cmd: call "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
  - cmd: nuget restore
  - cmd: dir /s "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Community\VC\Redist\MSVC\"

build:
  project: winlame.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: bin\Release\win*.dll
- path: bin\Release\win*.exe
- path: bin\Release\pdb\win*.pdb
- path: bin\Release\*.msi
