#
# winLAME - a frontend for the LAME encoding engine
# Copyright (c) 2000-2018 Michael Fink
#
# AppVeyor build configuration file
#
version: 2.18.1.{build}

image: Visual Studio 2017

platform: Win32

configuration: Release

before_build:
  - nuget restore

build:
  project: winlame.sln
  parallel: true
  verbosity: minimal

artifacts:
- path: bin\Release\win*.dll
- path: bin\Release\win*.exe
- path: bin\Release\pdb\win*.pdb
- path: bin\Release\*.msi
